#!/usr/bin/env bash
# script to install and setup nginx

CONFIG_FILE="/etc/nginx/sites-available/default"
# install nginx
apt-get -y update
apt-get -y install nginx

# update index.html file
echo 'Hello World' > /var/www/html/index.html

# update config file to redirect
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html/;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://github.com/sprusrxeroxx;
    }

}" > $CONFIG_FILE

# start nginx after reloading config
service nginx start