#!/usr/bin/env bash
# Installs nginx web server and sets up a simple web page with a redirect to my github page

apt-get update
apt-get install -y nginx
echo "Hello World" > /etc/nginx/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://github.com/sprusrxeroxx;
    }
}" > /etc/nginx/sites-available/default
service nginx restart