#!/usr/bin/env bash
# script to install and setup nginx
CONFIG_FILE="/etc/nginx/sites-available/default"
# install nginx
apt-get -y update
apt-get -y install nginx

# update index.html file
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# update config file to redirect
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html;

    location /redirect_me {
        return 301 https://github.com/sprusrxeroxx;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > $CONFIG_FILE

# start nginx after reloading config
service nginx start