#!/usr/bin/env bash
#a Bash script that pings an IP address passed as an argument

IP="${1}"

f=$(basename "${BASH_SOURCE[@]}")

if ! [ "$IP" ]; then
	echo "Usage: ${f} {IP_ADDRESS}"
else
	ping -c 5 "${IP}"
fi
