#!/usr/bin/env bash
#  a Bash script that displays To infinity and beyond indefinitely.

id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Terminate the infinate process
if [ -n "$id" ]
then
	  kill -15 "$id"
fi
