#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 100

y="Fizz"
z="Buzz"
rem_1=0
rem_2=0

for  x  in {1..100}; do
	rem_1=$(($x % 3))
	rem_2=$(($x % 5))

	if [ "$rem_1" -eq 0 ] && [ "$rem_2" -eq 0 ]; then
		echo "$y""$z"

	elif [ $rem_2 -eq 0 ]; then
		echo "$z"

	elif [ "$rem_1" -eq 0 ]; then
		echo "$y"
	else
		echo "$x"
	fi
done
