#!/usr/bin/env bash
# This script is displaying "Best School" 8 times and prints "bad luck" or "good luck" for others

x=1;
while [ $x  -le 10 ]
do
	echo "Best School"
	if [ $x == 4 ]; then
		echo "bad luck"
	elif [ $x == 8 ]; then
		echo "good luck"
	fi
	((x++))

done
